storage:
  postgres:
    postgres_db:
      username:
        env: DAGSTER_POSTGRES_USER
      password:
        env: DAGSTER_POSTGRES_PASSWORD
      hostname:
        env: DAGSTER_POSTGRES_HOST
      db_name:
        env: DAGSTER_POSTGRES_DB
      port:
        env: DAGSTER_POSTGRES_PORT

run_coordinator:
  module: dagster.core.run_coordinator
  class: QueuedRunCoordinator

scheduler:
  module: dagster.core.scheduler
  class: DagsterDaemonScheduler

telemetry:
  enabled: false
